### ISSUE TITLE
Frame buffer full - Error

### ISSUE THREAD

**Issue by Pablo923** [melexis-fir/mlx9064x-driver-py#1]
Hi, 

I try to read frames with raspberry pi connecting EVB9640 by USB and plot it. I can to read frames but I have an error that to say: ERROR: EVB90640: EVB Frame buffer full and I don't know how to fix it. I hope somebody help me.

**Comment by mlx-kva** [comment]
Hello @Pablo923,

Our team is relatively new to hosting public github repos. Sorry for the delay in this answer.

This happens typically when the PC (RPi) cannot follow emptying the buffer of EVB90640. Probably the plotting function takes quite some time, and hence the error.

A solution I used is the following construction:
```py
try:
  frame = dev.read_frame()
except:
  dev.clear_error(frame_rate)
  print("error")
else:
  if frame is not None:
    # handle your frame
```
Let me know if this solved the issue.

**Comment by jwhendy** [comment]
Greetings, I can open a separate issue if you'd like, but this is essentially what I'm running into but I wasn't plotting. I was purely trying to run `dev.read_frame()` and then `dev.do_compensation()` to inspect the output (I'm just getting started with this device). Is the `do_compensation()` call sufficiently long to cause this issue?

Put another way, can I run only this as many times as I want and I shouldn't run into the issue?
```
frame = dev.read_frame()
f = dev.do_compensation(frame)
```

Thanks, and let me know if you prefer a new issue.

**Edit:** thought to add that I'm doing this via linux using `/dev/ttyACM0` (USB). I was just re-reading the readme and saw the note on cache for what appears to be USB only, so I thought this might be relevant and it won't happen once I switch to I2C on an rpi.

**Comment by mlx-kva** [comment]
Should be no problem.
Did you add the try/except/else concept as in the message from feb 10th?

**Comment by jwhendy** [comment]
I am sure that will work, I'm just confused as to the root cause. It sounded like if one has code that takes a long time from the previous read to the next, something goes awry? I'm just trying to understand the what causes it to fail if you wait to long for a subsequent read. Many thanks.

**Comment by mlx-kva** [comment]
It is only applicable for the EVB, as that firmware has a buffer and it generates an error which needs to be cleared.
When you use the 'bare' device via I2C interface, when the host MCU (Raspberry Pi) is not fast enough, you simply have a missed frame, but show goes on... 
Note that you can update the refresh rate, upon needs or even to match the computing/analysing time.
