### ISSUE TITLE
Error using I2C Interface

### ISSUE THREAD

**Issue by morallito** [melexis-fir/mlx9064x-driver-py#2]
Hi, I'm trying to use the driver with I2C interface. My camera is a MLX900640.

I've installed the lib using pip3 install 
```
 pip install mlx9064x-driver
```

My code is :

```python
import mlx.mlx90640 as mlx
dev = mlx.Mlx9064x('I2C-1', i2c_addr=0x33, frame_rate=8.0) # establish communication between EVB90640 and
                                                          # PC, the I2C address of the MLX90640 sensor is
                                                          # 0x33 and change the frame rate to 8Hz
dev.init()                      # read EEPROM and pre-compute calibration parameters.
frame = dev.read_frame()        # Read a frame from MLX90640
                                # In case EVB90640 hw is used, the EVB will buffer up to 4 frames, so possibly you get a cached frame.
f = dev.do_compensation(frame)  # calculates the temperatures for each pixel
```

And I'm giving the following error:

```
Traceback (most recent call last):
  File "main.py", line 2, in <module>
    dev = mlx.Mlx9064x('I2C-1', i2c_addr=0x33, frame_rate=8.0) # establish communication between EVB90640 and
  File "/home/pi/.local/lib/python3.7/site-packages/mlx/mlx90640.py", line 44, in __init__
    if self.hw.get_sensor_type(0x33) == 0:
AttributeError: 'HwRpiI2cHw' object has no attribute 'get_sensor_type'
```

What is wrong?

**Comment by mlx-kva** [comment]
Hello @morallito, 

Not sure, I will try to reproduce.
What hardware do you use? Raspberry Pi? Which model?
Can you tell what the version is of the OS?

The output of `python --version` and `pip freeze` would be nice to have too.

Thanks,
K.

**Comment by morallito** [comment]
Hardware: 
Raspberry pi model 3 b+
Python 3.7.3

From pip freeze:
arandr==0.1.9
asn1crypto==0.24.0
automationhat==0.2.0
blinker==1.4
blinkt==0.1.2
buttonshim==0.0.2
Cap1xxx==0.1.3
certifi==2018.8.24
chardet==3.0.4
Click==7.0
colorama==0.3.7
colorzero==1.1
configparser==3.5.0b2
cookies==2.2.1
cryptography==2.6.1
drumhat==0.1.0
entrypoints==0.3
enum34==1.1.6
envirophat==1.0.0
ExplorerHAT==0.4.2
Flask==1.0.2
fourletterphat==0.1.0
funcsigs==1.0.2
gpiozero==1.5.1
gyp==0.1
idna==2.6
ipaddress==1.0.17
itsdangerous==0.24
Jinja2==2.10
keyring==17.1.1
keyrings.alt==3.1.1
MarkupSafe==1.1.0
mcpi==0.1.1
microdotphat==0.2.1
mock==2.0.0
mote==0.0.4
motephat==0.0.2
numpy==1.16.2
oauthlib==2.1.0
olefile==0.46
pantilthat==0.0.7
pbr==4.2.0
phatbeat==0.1.1
pianohat==0.1.0
picamera==1.13
picraft==1.0
piglow==1.2.5
pigpio==1.44
Pillow==5.4.1
pycairo==1.16.2
pycrypto==2.6.1
pyflakes==2.0.0
pygame==1.9.4.post1
PyGObject==3.30.4
pyinotify==0.9.6
PyJWT==1.7.0
pyOpenSSL==19.0.0
pyserial==3.4
pyxdg==0.25
rainbowhat==0.1.0
requests==2.21.0
requests-oauthlib==1.0.0
responses==0.9.0
RPi.GPIO==0.7.0
RTIMULib==7.2.1
scrollphat==0.0.7
scrollphathd==1.2.1
SecretStorage==2.3.1
sense-emu==1.1
sense-hat==2.2.0
simplejson==3.16.0
six==1.12.0
skywriter==0.0.7
sn3218==1.2.7
spidev==3.4
touchphat==0.0.1
twython==3.7.0
unicornhathd==0.0.4
urllib3==1.24.1
Werkzeug==0.14.1

**Comment by mlx-kva** [comment]
Hello, can you try V1.2.4 of mlx9064x-driver?

**Comment by morallito** [comment]
Thanks, worked with V1.2.4 Driver. Sorry for late, but i was working on other projects!

**Comment by mlx-kva** [comment]
No issue you are still way faster than me!
I'm happy it works now for you too.
