### ISSUE TITLE
Reading Raw Frame 

### ISSUE THREAD

**Issue by Pidv** [melexis-fir/mlx9064x-driver-py#7]
Hi, I am doing a project with an MLX90640 camera sensor.
I am using EVB90640-41 on the Windows platform. I want to get the raw data from each sub-page of the sensor.  Could you please help me to do it with your libraries?
Thanks for spending time checking my question.

**Comment by mlx-kva** [comment]
Please use this package in stead https://github.com/melexis-fir/mlx90640-driver-evb9064x-py

Reading raw data for each subpage individually is not supported by our driver.
You might get inspired by this:
https://github.com/melexis-fir/mlx90640-driver-py/blob/master/mlx90640/c-code/src/MLX90640_API.c#L113
and the datasheet, should you want to read only one sub-page.

**Comment by Pidv** [comment]
Many thanks for your support.

Vào Th 2, 5 thg 7, 2021 vào lúc 20:31 mlx-kva ***@***.***>
đã viết:
