### ISSUE TITLE
The delay is serious when the frame rate is 32 or 64

### ISSUE THREAD

**Issue by mokems** [melexis-fir/mlx9064x-driver-py#9]
I use the code to get the frame and show the image, but the delay is very serious. Is there any way to fix it?
```
while(True):
      try:
          frame = dev.read_frame()
      except:
          dev.clear_error(32.0)
      else:
          if frame!=None:
              i+=1
              f = dev.do_compensation(frame)
              show_list_as_image(f) 
```

**Comment by mokems** [comment]
The frame_rate is 32 or 64. But when set to 16 frames, there will be no delay.

**Comment by karelv** [comment]
@mokems This is a known issue, basically the `do_compensate` function does all the calculations in python, and that takes a while.  You can use the C-driver functions to fix that, but I don't have a python binding to those C-functions.

**Comment by karelv** [comment]
Feel free to make a PR, if you find a solution.
